---

- name: "PRELIM | Enable Domain firewall profile"
  win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: EnableFirewall
      data: 1
      type: dword
  when:
      - ansible_windows_domain_member
      - winfwadvsecstig_cat1_patch or
        winfwadvsecstig_cat2_patch
      - wnfwa_000004 or
        wnfwa_000001 or
        wnfwa_000005

- name: "PRELIM | Enable Private firewall profile"
  win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: EnableFirewall
      data: 1
      type: dword
  when:
      - winfwadvsecstig_cat1_patch or
        winfwadvsecstig_cat2_patch
      - wnfwa_000012 or
        wnfwa_000002 or
        wnfwa_000013

- name: "PRELIM | Enable Public firewall profile"
  win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
      name: EnableFirewall
      data: 1
      type: dword
  when:
      - winfwadvsecstig_cat1_patch or
        winfwadvsecstig_cat2_patch
      - wnfwa_000020 or
        wnfwa_000003 or
        wnfwa_000021 or
        wnfwa_000024 or
        wnfwa_000025
